#!/usr/bin/python

import sys,os
import openfst

Fst = openfst.StdVectorFst

prefix = Fst()
prefix.AddString("",0.0)
prefix.AddString("'",9.0)
prefix.AddString("\"",9.0)

dict = Fst()
for line in open("wordcosts").readlines():
    line = line[:-1]
    cost,word = line.split()
    cost = float(cost)
    dict.AddString(word,cost)
    if word!=word.upper():
        dict.AddString(word.upper(),cost+4.0)
    if word!=word.lower():
        dict.AddString(word.lower(),cost+4.0)

openfst.ConcatOnto(prefix,dict)
dict = prefix

suffix = Fst()
suffix.AddString("",0.0)
suffix.AddString("s",5.0)
suffix.AddString("'s",5.0)
suffix.AddString("ly",9.0)
suffix.AddString("ing",9.0)
suffix.AddString("es",9.0)
suffix.AddString("'nt",9.0)
suffix.AddString("'ve",9.0)
openfst.ConcatOnto(dict,suffix)

sep = Fst()
sep.AddString(" ",0.0)
sep.AddString(". ",4.0)
sep.AddString(", ",4.0)
sep.AddString(": ",9.0)
sep.AddString("; ",9.0)
sep.AddString("? ",9.0)
sep.AddString("! ",9.0)
sep.AddString("\" ",9.0)
sep.AddString(" \"",9.0)
sep.AddString("' ",9.0)
sep.AddString(" '",9.0)
sep.AddString("\"",11.0)
sep.AddString("'",11.0)
sep.AddString("",14.0)
openfst.ConcatOnto(dict,sep)
openfst.ClosurePlus(dict)

det = Fst()
openfst.Determinize(dict,det)
openfst.Minimize(det)

det.Write("dict.fst")
