#!/usr/bin/python2.5

import sys,os
import openfst

str = openfst.StdVectorFst()
openfst.AddString(str,sys.argv[1])

fst = openfst.Read(sys.argv[2])

openfst.ArcSortOutput(str)
openfst.ArcSortInput(fst)

result = openfst.StdVectorFst()
openfst.Compose(fst,str,result)

best = openfst.StdVectorFst()
openfst.ShortestPath(result,best,1)

print openfst.GetString(best)
